events {}

http {
    #configuracion para el balanceador de carga (conjunto de servidores)
    upstream servidores {
        #servicios docker compose
        #puerto configurado en el docker file
        server formulario:8100 weight=2;
        server formulario2:8100 weight=3;      
    }

    server{
        #proxypass entre el grupo de servidores
        listen 80;
        location /{
            proxy_pass http://servidores;
        }
    }
}